FROM ubuntu:18.10

# Actualizar los repositorios a los de old-releases
RUN sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/old-releases.ubuntu.com/g' /etc/apt/sources.list
RUN sed -i 's/http:\/\/security.ubuntu.com/http:\/\/old-releases.ubuntu.com/g' /etc/apt/sources.list

# Actualizar e instalar openssh-client y tshark
RUN apt-get update && apt-get install -y openssh-client tshark
